#islandora_web_annotations

sudo: true

language: php

php:
  - 5.3.3
  - 5.4
  - 5.5

branches:
  only:
    - issue-25


script:
  - ant -buildfile sites/all/modules/islandora_solution_pack_oralhistories/build.xml lint

